# The services of the project.
#
# Each service listed will be deployed
# to power your Platform.sh project.

db:
    type: mariadb:10.4
    disk: 2048

cache:
    type: redis:6.0

solr:
  type: solr:7.7
  disk: 1024
  configuration:
    cores:
      drupal:
        conf_dir: !archive "configsets/solr7"
    endpoints:
      solr:
        core: drupal
searchelastic:
    type: elasticsearch:7.9
    disk: 1024